<?php

namespace App\Libraries;

use CodeIgniter\I18n\Time;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

/**
 * ExcelExportService
 *
 * Generates a detailed Excel workbook for a SmartSplit monthly final distribution.
 *
 * Sheets produced:
 *   1. Summary          — one row per user: expenses + advance → final
 *   2. Expenses         — PIVOT layout: rows = members, columns grouped by expense type.
 *                         Row 4 = type name header. Row 5 = billing_month sub-header.
 *                         Each type group: member's sum across all entries of that type.
 *                         Only types with ≥1 entry that month appear. Grand Total rightmost col.
 *   3. Raw Data         — machine-readable version of summary (for future import/reference)
 *                         Includes billing_month column (= the distribution month, repeated per row).
 *
 * Usage:
 *   $svc = new ExcelExportService();
 *   $path = $svc->generate($month, $data);   // $data from FinalDistribution controller
 *   // stream $path to browser, then unlink
 */
class ExcelExportService
{
    // ── Brand palette ──────────────────────────────────────────────────────────
    private const NAVY = '1A1B4B';
    private const INDIGO = '5C6AF0';
    private const PERIWINKLE = 'A5BBFB';
    private const LIGHT_BG = 'F0F4FF';
    private const WHITE = 'FFFFFF';
    private const DARK_TEXT = '1E2040';
    private const MID_TEXT = '4B5280';
    private const GREEN_BG = 'D1FAE5';
    private const GREEN_FG = '065F46';
    private const RED_BG = 'FEE2E2';
    private const RED_FG = '991B1B';
    private const YELLOW_BG = 'FEF3C7';
    private const YELLOW_FG = '92400E';

    // Lighter tint used for billing_month sub-header row in Sheet 2.
    private const INDIGO_SOFT = 'C7D2FE'; // indigo-200 equivalent
    private const GT_TINT = 'E0E7FF';     // indigo-100 — sets Grand Total column apart
    private const MONEY_FMT = '"₹"#,##0.00;[RED]-"₹"#,##0.00'; // currency w/ accounting-style negatives

    private Spreadsheet $wb;

    // ── Public entry point ─────────────────────────────────────────────────────

    /**
     * Generate the Excel file and return the temp file path.
     *
     * @param  string $month Format: YYYY-MM
     * @param  array  $data  Full payload from the FinalDistribution controller.
     *                       Keys expected:
     *                         users         array of user rows (id, name)
     *                         distributions array keyed by user_id with
     *                                       expenses_amount, advance_amount,
     *                                       final_amount
     *                         expenses      array from buildExpenseDetail() — each has
     *                                       id, expense_type, amount, from_date,
     *                                       to_date, paid_by_name, split_method,
     *                                       billing_month,
     *                                       user_shares (user_id => share_amount)
     * @return string Absolute path to the temp .xlsx file
     */
    public function generate(string $month, array $data): string
    {
        $this->wb = new Spreadsheet();
        $this->wb->getProperties()
            ->setCreator('SmartSplit')
            ->setTitle("SmartSplit — {$month}")
            ->setSubject("Final Distribution {$month}")
            ->setDescription('Generated by SmartSplit expense splitting system');

        $this->wb->getDefaultStyle()->getFont()->setName('Arial')->setSize(10);

        $users = $data['users'] ?? [];
        $distributions = $data['distributions'] ?? [];
        $expenses = $data['expenses'] ?? [];

        // Remove the default blank sheet; we'll add our own.
        $this->wb->removeSheetByIndex(0);

        $this->buildSummarySheet($month, $users, $distributions);
        $this->buildExpensesSheet($month, $users, $expenses);
        $this->buildRawDataSheet($month, $users, $distributions);

        // Activate first sheet.
        $this->wb->setActiveSheetIndex(0);

        $tmpPath = WRITEPATH . '/smartsplit_' . $month . '_' . time() . '.xlsx';
        (new Xlsx($this->wb))->save($tmpPath);

        return $tmpPath;
    }

    // ══════════════════════════════════════════════════════════════════════════
    // SHEET 1 — SUMMARY
    //
    // Columns: # | Member | Expenses (₹) | Advance Paid (₹) | Final Amount (₹) | Status
    // ══════════════════════════════════════════════════════════════════════════

    private function buildSummarySheet(string $month, array $users, array $distributions): void
    {
        $ws = $this->wb->createSheet();
        $ws->setTitle('Summary');
        $ws->getTabColor()->setRGB(self::INDIGO);

        [$yr, $mo] = explode('-', $month);
        $monthLabel = date('F Y', mktime(0, 0, 0, (int) $mo, 1, (int) $yr));

        // ── Cover header block ────────────────────────────────────────────────
        $ws->mergeCells('A1:F1');
        $ws->setCellValue('A1', 'SmartSplit — Monthly Distribution Report');
        $this->styleCell($ws, 'A1', [
            'font' => ['bold' => true, 'size' => 16, 'color' => self::WHITE],
            'fill' => self::NAVY,
            'alignment' => 'center',
        ]);
        $ws->getRowDimension(1)->setRowHeight(36);

        $ws->mergeCells('A2:F2');
        $ws->setCellValue('A2', $monthLabel);
        $this->styleCell($ws, 'A2', [
            'font' => ['bold' => true, 'size' => 13, 'color' => self::PERIWINKLE],
            'fill' => self::NAVY,
            'alignment' => 'center',
        ]);
        $ws->getRowDimension(2)->setRowHeight(24);

        $ws->mergeCells('A3:F3');
        $ws->setCellValue('A3', 'Generated on: ' . Time::now()->toLocalizedString('dd MMM yyyy, HH:mm'));
        $this->styleCell($ws, 'A3', [
            'font' => ['size' => 9, 'color' => self::PERIWINKLE, 'italic' => true],
            'fill' => self::NAVY,
            'alignment' => 'center',
        ]);
        $ws->getRowDimension(3)->setRowHeight(18);

        $ws->getRowDimension(4)->setRowHeight(10);

        // ── Table header ──────────────────────────────────────────────────────
        $headers = ['#', 'Member', 'Expenses (₹)', 'Advance Paid (₹)', 'Final Amount (₹)', 'Status'];
        $cols = ['A', 'B', 'C', 'D', 'E', 'F'];

        foreach ($headers as $i => $h) {
            $cell = $cols[$i] . '5';
            $ws->setCellValue($cell, $h);
            $this->styleCell($ws, $cell, [
                'font' => ['bold' => true, 'color' => self::WHITE, 'size' => 10],
                'fill' => self::INDIGO,
                'alignment' => $i === 1 ? 'left' : 'center',
                'border' => 'all_thin',
            ]);
        }
        $ws->getRowDimension(5)->setRowHeight(22);

        // ── Data rows ─────────────────────────────────────────────────────────
        $row = 6;
        $total = $totalAdvance = $totalFinal = 0.0;

        foreach ($users as $idx => $user) {
            $uid = $user['id'];
            $dist = $distributions[$uid] ?? [];

            $expenses = (float) ($dist['expenses_amount'] ?? 0);
            $advance = (float) ($dist['advance_amount'] ?? 0);
            $final = (float) ($dist['final_amount'] ?? 0);

            $total += $expenses;
            $totalAdvance += $advance;
            $totalFinal += $final;

            $bgFill = ($idx % 2 === 0) ? self::WHITE : self::LIGHT_BG;

            $ws->setCellValue("A{$row}", $idx + 1);
            $ws->setCellValue("B{$row}", $user['name']);
            $ws->setCellValue("C{$row}", $expenses);
            $ws->setCellValue("D{$row}", $advance);
            $ws->setCellValue("E{$row}", $final);

            if ($final > 0.009) {
                $status = 'OWES ₹' . number_format($final, 2);
                $statusFill = self::RED_BG;
                $statusColor = self::RED_FG;
            } elseif ($final < -0.009) {
                $status = 'CREDIT ₹' . number_format(abs($final), 2);
                $statusFill = self::GREEN_BG;
                $statusColor = self::GREEN_FG;
            } else {
                $status = 'SETTLED';
                $statusFill = self::YELLOW_BG;
                $statusColor = self::YELLOW_FG;
            }
            $ws->setCellValue("F{$row}", $status);

            foreach ($cols as $ci => $col) {
                $cell = "{$col}{$row}";
                $style = ['fill' => $bgFill, 'border' => 'all_thin', 'color' => self::DARK_TEXT];
                if ($ci === 1) {
                    $style['alignment'] = 'left';
                } elseif ($ci === 5) {
                    $style['fill'] = $statusFill;
                    $style['color'] = $statusColor;
                    $style['alignment'] = 'center';
                    $style['font'] = ['bold' => true, 'size' => 9];
                } else {
                    $style['alignment'] = 'right';
                    $style['format'] = '#,##0.00';
                }
                $this->styleCell($ws, $cell, $style);
            }
            $ws->getRowDimension($row)->setRowHeight(20);
            $row++;
        }

        // ── Totals row ────────────────────────────────────────────────────────
        $ws->setCellValue("A{$row}", '');
        $ws->setCellValue("B{$row}", 'TOTAL');
        $ws->setCellValue("C{$row}", $total);
        $ws->setCellValue("D{$row}", $totalAdvance);
        $ws->setCellValue("E{$row}", $totalFinal);
        $ws->setCellValue("F{$row}", '');

        foreach ($cols as $ci => $col) {
            $cell = "{$col}{$row}";
            $style = ['fill' => self::NAVY, 'color' => self::WHITE, 'border' => 'all_thin', 'font' => ['bold' => true]];
            if ($ci > 1 && $ci < 5) {
                $style['alignment'] = 'right';
                $style['format'] = '#,##0.00';
            } elseif ($ci === 1) {
                $style['alignment'] = 'left';
            }
            $this->styleCell($ws, $cell, $style);
        }
        $ws->getRowDimension($row)->setRowHeight(22);

        // ── Column widths ─────────────────────────────────────────────────────
        $ws->getColumnDimension('A')->setWidth(5);
        $ws->getColumnDimension('B')->setWidth(22);
        $ws->getColumnDimension('C')->setWidth(22);
        $ws->getColumnDimension('D')->setWidth(22);
        $ws->getColumnDimension('E')->setWidth(22);
        $ws->getColumnDimension('F')->setWidth(22);

        // ── Legend block ──────────────────────────────────────────────────────
        $legendRow = $row + 2;
        $ws->mergeCells("A{$legendRow}:F{$legendRow}");
        $ws->setCellValue("A{$legendRow}", 'Legend');
        $this->styleCell($ws, "A{$legendRow}", [
            'font' => ['bold' => true, 'size' => 10, 'color' => self::DARK_TEXT],
            'fill' => self::PERIWINKLE,
        ]);

        $legends = [
            ['OWES', 'User\'s total share exceeds their advance — they owe this amount to the house.', self::RED_BG, self::RED_FG],
            ['CREDIT', 'User paid more than their share — the house owes them this amount.', self::GREEN_BG, self::GREEN_FG],
            ['SETTLED', 'User\'s share and advance are equal — nothing to pay or receive.', self::YELLOW_BG, self::YELLOW_FG],
        ];

        foreach ($legends as $leg) {
            $legendRow++;
            $ws->mergeCells("A{$legendRow}:B{$legendRow}");
            $ws->setCellValue("A{$legendRow}", $leg[0]);
            $this->styleCell($ws, "A{$legendRow}", [
                'fill' => $leg[2],
                'color' => $leg[3],
                'font' => ['bold' => true],
                'border' => 'all_thin',
            ]);
            $ws->mergeCells("C{$legendRow}:F{$legendRow}");
            $ws->setCellValue("C{$legendRow}", $leg[1]);
            $this->styleCell($ws, "C{$legendRow}", [
                'fill' => self::WHITE,
                'color' => self::MID_TEXT,
                'font' => ['italic' => true, 'size' => 9],
                'border' => 'all_thin',
            ]);
            $ws->getRowDimension($legendRow)->setRowHeight(18);
        }

        // ── Notes block ───────────────────────────────────────────────────────
        $noteRow = $legendRow + 2;
        $notes = [
            '• Expenses = Your share of household expenses (groceries, bills, etc.), split equally or by days present.',
            '• Advance Paid = Total amount you paid upfront (recorded as paid_by on expense records).',
            '• Final Amount = Expenses − Advance. Positive means you owe; negative means you are in credit.',
        ];
        foreach ($notes as $note) {
            $ws->mergeCells("A{$noteRow}:F{$noteRow}");
            $ws->setCellValue("A{$noteRow}", $note);
            $this->styleCell($ws, "A{$noteRow}", [
                'color' => self::MID_TEXT,
                'font' => ['size' => 9, 'italic' => true],
            ]);
            $ws->getRowDimension($noteRow)->setRowHeight(16);
            $noteRow++;
        }

        $ws->freezePane('A6'); // header row stays visible while scrolling members
        $ws->setSelectedCell('A1');
    }

    // ══════════════════════════════════════════════════════════════════════════
    // SHEET 2 — EXPENSES BREAKDOWN
    //
    // Layout:
    //   Row 1 : Sheet title
    //   Row 2 : Subtitle
    //   Row 4 : Type name header — Name | <Type1> | <Type2> | ... | Grand Total
    //   Row 5 : Billing month sub-header — blank | <YYYY-MM> | <YYYY-MM> | ... | blank
    //   Row 6+: One row per member — name + summed share per type + grand total
    //   Last  : TOTAL footer row
    //
    //   If a type has expenses across multiple billing_months (shouldn't happen
    //   since the calculator filters by billing_month, but handled gracefully),
    //   the sub-header shows them comma-separated.
    // ══════════════════════════════════════════════════════════════════════════

    private function buildExpensesSheet(string $month, array $users, array $expenses): void
    {
        $ws = $this->wb->createSheet();
        $ws->setTitle('Expenses');
        $ws->getTabColor()->setRGB(self::INDIGO);

        [$yr, $mo] = explode('-', $month);
        $monthLabel = date('F Y', mktime(0, 0, 0, (int) $mo, 1, (int) $yr));

        $userIds = array_column($users, 'id');

        // ── Step 1: Pre-aggregate ─────────────────────────────────────────────
        // memberShare[$typeName][$uid]    = sum of member's shares across all expenses of that type
        // typeBillingMonths[$typeName]    = array of distinct billing_month values seen for that type
        //                                   (deduplicated; in practice should always be one value
        //                                   since the calculator groups by billing_month)

        $memberShare = []; // typeName => [ uid => float ]
        $typeBillingMonths = []; // typeName => [ billing_month => true ]  (set semantics)

        foreach ($expenses as $exp) {
            $typeName = $exp['expense_type'] ?? 'Unknown';
            $billingMonth = $exp['billing_month'] ?? $month;

            if (!isset($memberShare[$typeName])) {
                $memberShare[$typeName] = array_fill_keys($userIds, 0.0);
                $typeBillingMonths[$typeName] = [];
            }

            // Collect distinct billing months per type.
            $typeBillingMonths[$typeName][$billingMonth] = true;

            foreach ($userIds as $uid) {
                $memberShare[$typeName][$uid] += (float) ($exp['user_shares'][$uid] ?? 0.0);
            }
        }

        $types = array_keys($memberShare);
        $typeCount = count($types);

        // ── Step 2: Column index map ──────────────────────────────────────────
        // Col 1 (A) = Name
        // Col 2..N  = one per type
        // Col N+1   = Grand Total

        $typeCol = [];
        foreach ($types as $ti => $typeName) {
            $typeCol[$typeName] = 2 + $ti;
        }
        $grandTotalCol = 2 + $typeCount;
        $lastCol = $this->colLetter($grandTotalCol);

        // ── Step 3: Title rows ────────────────────────────────────────────────
        $ws->mergeCells("A1:{$lastCol}1");
        $ws->setCellValue('A1', "Expenses Breakdown — {$monthLabel}");
        $this->styleCell($ws, 'A1', [
            'font' => ['bold' => true, 'size' => 14, 'color' => self::WHITE],
            'fill' => self::INDIGO,
            'alignment' => 'center',
        ]);
        $ws->getRowDimension(1)->setRowHeight(30);

        $ws->mergeCells("A2:{$lastCol}2");
        $ws->setCellValue('A2', 'One row per member. Each column = member\'s total share for that expense type. Row 5 shows the billing month for each type.');
        $this->styleCell($ws, 'A2', [
            'font' => ['size' => 9, 'italic' => true, 'color' => self::MID_TEXT],
            'fill' => self::LIGHT_BG,
            'alignment' => 'center',
        ]);
        $ws->getRowDimension(2)->setRowHeight(16);

        // Spacer row 3.
        $ws->getRowDimension(3)->setRowHeight(6);

        // ── Step 4: Type name header row (row 4) ──────────────────────────────
        $typeHdrRow = 4;

        $ws->setCellValue('A' . $typeHdrRow, 'Name');
        $this->styleCell($ws, 'A' . $typeHdrRow, [
            'font' => ['bold' => true, 'color' => self::WHITE, 'size' => 10],
            'fill' => self::NAVY,
            'alignment' => 'left',
            'border' => 'all_thin',
        ]);

        foreach ($types as $typeName) {
            $col = $this->colLetter($typeCol[$typeName]);
            $cell = $col . $typeHdrRow;
            $ws->setCellValue($cell, $typeName);
            $this->styleCell($ws, $cell, [
                'font' => ['bold' => true, 'color' => self::WHITE, 'size' => 10],
                'fill' => self::INDIGO,
                'alignment' => 'center',
                'border' => 'all_thin',
            ]);
        }

        $gtHdrCell = $lastCol . $typeHdrRow;
        $ws->setCellValue($gtHdrCell, 'Grand Total');
        $this->styleCell($ws, $gtHdrCell, [
            'font' => ['bold' => true, 'color' => self::WHITE, 'size' => 10],
            'fill' => self::NAVY,
            'alignment' => 'center',
            'border' => 'all_thin',
        ]);
        $ws->getRowDimension($typeHdrRow)->setRowHeight(22);

        // ── Step 5: Billing month sub-header row (row 5) ──────────────────────
        // Shows which billing_month(s) each type column covers.
        // "Name" cell and "Grand Total" cell are left blank (navy background to match).

        $billingHdrRow = 5;

        // Name cell — blank, navy.
        $ws->setCellValue('A' . $billingHdrRow, '');
        $this->styleCell($ws, 'A' . $billingHdrRow, [
            'fill' => self::NAVY,
            'border' => 'all_thin',
        ]);

        foreach ($types as $typeName) {
            $col = $this->colLetter($typeCol[$typeName]);
            $cell = $col . $billingHdrRow;

            // Collapse set keys to a sorted, comma-separated string.
            $months = array_keys($typeBillingMonths[$typeName] ?? []);
            sort($months);
            $billingLabel = implode(', ', $months) ?: $month;

            $ws->setCellValue($cell, $billingLabel);
            $this->styleCell($ws, $cell, [
                'font' => ['bold' => false, 'size' => 9, 'color' => self::DARK_TEXT, 'italic' => true],
                'fill' => self::INDIGO_SOFT,
                'alignment' => 'center',
                'border' => 'all_thin',
            ]);
        }

        // Grand Total cell — blank, navy.
        $ws->setCellValue($lastCol . $billingHdrRow, '');
        $this->styleCell($ws, $lastCol . $billingHdrRow, [
            'fill' => self::NAVY,
            'border' => 'all_thin',
        ]);

        $ws->getRowDimension($billingHdrRow)->setRowHeight(18);

        // ── Step 6: Data rows — one per member (start row 6) ─────────────────
        $dataRow = $billingHdrRow + 1;

        $footerType = array_fill_keys($types, 0.0);
        $footerTotal = 0.0;

        if (empty($expenses)) {
            $ws->mergeCells("A{$dataRow}:{$lastCol}{$dataRow}");
            $ws->setCellValue("A{$dataRow}", 'No expenses recorded for this month.');
            $this->styleCell($ws, "A{$dataRow}", [
                'color' => self::MID_TEXT,
                'alignment' => 'center',
                'font' => ['italic' => true],
            ]);
            $dataRow++;
        } else {
            foreach ($users as $idx => $user) {
                $uid = $user['id'];
                $bgFill = ($idx % 2 === 0) ? self::WHITE : self::LIGHT_BG;

                $ws->setCellValue('A' . $dataRow, $user['name']);
                $this->styleCell($ws, 'A' . $dataRow, [
                    'fill' => $bgFill,
                    'color' => self::DARK_TEXT,
                    'border' => 'all_thin',
                    'alignment' => 'left',
                ]);

                $memberTotal = 0.0;

                foreach ($types as $typeName) {
                    $col = $this->colLetter($typeCol[$typeName]);
                    $cell = $col . $dataRow;
                    $amount = $memberShare[$typeName][$uid];

                    $ws->setCellValue($cell, $amount);
                    $this->styleCell($ws, $cell, [
                        'fill' => $bgFill,
                        'color' => $amount < 0.005 ? self::MID_TEXT : self::DARK_TEXT,
                        'border' => 'all_thin',
                        'alignment' => 'right',
                        'format' => self::MONEY_FMT,
                    ]);

                    $memberTotal += $amount;
                    $footerType[$typeName] += $amount;
                }

                $gtCell = $lastCol . $dataRow;
                $ws->setCellValue($gtCell, $memberTotal);
                $this->styleCell($ws, $gtCell, [
                    'fill' => self::GT_TINT,
                    'color' => self::DARK_TEXT,
                    'border' => 'all_thin',
                    'alignment' => 'right',
                    'format' => self::MONEY_FMT,
                    'font' => ['bold' => true],
                ]);

                $footerTotal += $memberTotal;
                $ws->getRowDimension($dataRow)->setRowHeight(20);
                $dataRow++;
            }
        }

        // ── Step 7: TOTAL footer row ──────────────────────────────────────────
        $ws->setCellValue('A' . $dataRow, 'Total');
        $this->styleCell($ws, 'A' . $dataRow, [
            'fill' => self::NAVY,
            'color' => self::WHITE,
            'border' => 'all_thin',
            'alignment' => 'left',
            'font' => ['bold' => true],
        ]);

        foreach ($types as $typeName) {
            $col = $this->colLetter($typeCol[$typeName]);
            $cell = $col . $dataRow;
            $ws->setCellValue($cell, $footerType[$typeName]);
            $this->styleCell($ws, $cell, [
                'fill' => self::NAVY,
                'color' => self::WHITE,
                'border' => 'all_thin',
                'alignment' => 'right',
                'format' => self::MONEY_FMT,
                'font' => ['bold' => true],
            ]);
        }

        $gtFooter = $lastCol . $dataRow;
        $ws->setCellValue($gtFooter, $footerTotal);
        $this->styleCell($ws, $gtFooter, [
            'fill' => self::INDIGO,
            'color' => self::WHITE,
            'border' => 'all_thin',
            'alignment' => 'right',
            'format' => self::MONEY_FMT,
            'font' => ['bold' => true],
        ]);
        $ws->getRowDimension($dataRow)->setRowHeight(22);

        // ── Step 8: Column widths ─────────────────────────────────────────────
        $ws->getColumnDimension('A')->setWidth(22);
        foreach ($types as $typeName) {
            $ws->getColumnDimension($this->colLetter($typeCol[$typeName]))->setWidth(18);
        }
        $ws->getColumnDimension($lastCol)->setWidth(16);

        // Freeze Name column + both header rows while scrolling.
        $ws->freezePane('B' . ($billingHdrRow + 1));

        $ws->setSelectedCell('A1');
    }

    // ══════════════════════════════════════════════════════════════════════════
    // SHEET 3 — RAW DATA
    //
    // Column layout (1-based):
    //   A: month   B: user_id   C: billing_month   D: user_name
    //   E: expenses_amount   F: advance_amount
    //   G: final_amount   H: generated_at
    //
    // billing_month repeats $month for every user row — the distribution is
    // always generated for a single billing month, so every row is the same.
    // ══════════════════════════════════════════════════════════════════════════

    private function buildRawDataSheet(string $month, array $users, array $distributions): void
    {
        $ws = $this->wb->createSheet();
        $ws->setTitle('Raw Data');
        $ws->getTabColor()->setRGB(self::INDIGO);

        // ── Header row ────────────────────────────────────────────────────────
        $headers = [
            'A' => 'month',
            'B' => 'user_id',
            'C' => 'billing_month',
            'D' => 'user_name',
            'E' => 'expenses_amount',
            'F' => 'advance_amount',
            'G' => 'final_amount',
            'H' => 'generated_at',
        ];

        foreach ($headers as $col => $label) {
            $ws->setCellValue("{$col}1", $label);
            $this->styleCell($ws, "{$col}1", [
                'font' => ['bold' => true, 'color' => self::WHITE],
                'fill' => self::NAVY,
                'border' => 'all_thin',
            ]);
        }
        $ws->getRowDimension(1)->setRowHeight(20);

        // ── Data rows ─────────────────────────────────────────────────────────
        $row = 2;
        $now = Time::now()->toDateTimeString();

        foreach ($users as $idx => $user) {
            $uid = $user['id'];
            $dist = $distributions[$uid] ?? [];
            $bgFill = ($idx % 2 === 0) ? self::WHITE : self::LIGHT_BG;

            $ws->setCellValue("A{$row}", $month);
            $ws->setCellValue("B{$row}", $uid);
            $ws->setCellValue("C{$row}", $month);
            $ws->setCellValue("D{$row}", $user['name']);
            $ws->setCellValue("E{$row}", (float) ($dist['expenses_amount'] ?? 0));
            $ws->setCellValue("F{$row}", (float) ($dist['advance_amount'] ?? 0));
            $ws->setCellValue("G{$row}", (float) ($dist['final_amount'] ?? 0));
            $ws->setCellValue("H{$row}", $now);

            foreach ($headers as $ci => $col) {
                $style = ['border' => 'all_thin', 'color' => self::DARK_TEXT, 'fill' => $bgFill];
                if (in_array($ci, ['E', 'F', 'G'], true)) {
                    $style['alignment'] = 'right';
                    $style['format'] = self::MONEY_FMT;
                }
                $this->styleCell($ws, "{$ci}{$row}", $style);
            }

            $ws->getRowDimension($row)->setRowHeight(18);
            $row++;
        }

        // ── Column widths ─────────────────────────────────────────────────────
        $widths = [
            'A' => 12, // month
            'B' => 10, // user_id
            'C' => 14, // billing_month
            'D' => 22, // user_name
            'E' => 22, // expenses_amount
            'F' => 18, // advance_amount
            'G' => 16, // final_amount
            'H' => 20, // generated_at
        ];
        foreach ($widths as $col => $w) {
            $ws->getColumnDimension($col)->setWidth($w);
        }

        $lastDataRow = $row - 1;
        if ($lastDataRow >= 2) {
            $ws->setAutoFilter("A1:H{$lastDataRow}");
        }
        $ws->freezePane('A2');
        $ws->setSelectedCell('A1');
    }

    // ══════════════════════════════════════════════════════════════════════════
    // HELPERS
    // ══════════════════════════════════════════════════════════════════════════

    /**
     * Unified cell styling helper.
     * $opts keys: font (array), fill (hex string), color (hex text), border,
     *             alignment (left|center|right), format (number format string)
     */
    private function styleCell(Worksheet $ws, string $cell, array $opts): void
    {
        $style = $ws->getStyle($cell);

        if (!empty($opts['font'])) {
            $fo = $opts['font'];
            $f = $style->getFont();
            if (!empty($fo['bold'])) {
                $f->setBold(true);
            }
            if (!empty($fo['italic'])) {
                $f->setItalic(true);
            }
            if (!empty($fo['size'])) {
                $f->setSize($fo['size']);
            }
            if (!empty($fo['color'])) {
                $f->getColor()->setRGB($fo['color']);
            }
        }
        if (!empty($opts['color'])) {
            $style->getFont()->getColor()->setRGB($opts['color']);
        }
        if (!empty($opts['fill'])) {
            $style->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB($opts['fill']);
        }
        if (!empty($opts['border'])) {
            $style->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
        }
        if (!empty($opts['alignment'])) {
            $h = match ($opts['alignment']) {
                'center' => Alignment::HORIZONTAL_CENTER,
                'right' => Alignment::HORIZONTAL_RIGHT,
                default => Alignment::HORIZONTAL_LEFT,
            };
            $style->getAlignment()->setHorizontal($h)->setVertical(Alignment::VERTICAL_CENTER);
        }
        if (!empty($opts['format'])) {
            $style->getNumberFormat()->setFormatCode($opts['format']);
        }
    }

    /**
     * Convert 1-based column index to Excel letter(s).
     * 1=A, 26=Z, 27=AA, etc.
     */
    private function colLetter(int $n): string
    {
        $letters = '';
        while ($n > 0) {
            $n--;
            $letters = chr(65 + ($n % 26)) . $letters;
            $n = (int) ($n / 26);
        }

        return $letters;
    }
}
